### ISSUE TITLE
Member receives a notification about an event

### ISSUE THREAD

**Issue by stinerz** [pele1250/Join-Us#16]

**Comment by mightyjames** [comment]
User can receive a notification for any of the following:
- Before an event is about to start to remind the user of that event
- When one of their friends in their friends list has decided to join an event
- Whenever the user has been invited to join an event by one of their friends
- When an event, that the user is currently planning on attending, has been altered or deleted

**Comment by pele1250** [comment]
No enough time left to complete feature before final release date.
