### ISSUE TITLE
Member searches for an event

### ISSUE THREAD

**Issue by stinerz** [pele1250/Join-Us#9]
Users can search for events that can be filtered by keywords, location distance, and tags. When viewing the search results they can also see little notices of which of their friends are planning on going otherwise they will only see the number of people that are planning on going.

**Comment by mightyjames** [comment]
Users can search for events that can be filtered by keywords, location distance, and tags. When viewing the search results they can also see little notices of which of their friends are planning on going otherwise they will only see the number of people that are planning on going.
